-- Mark specific programs as accreditable.
-- Idempotent update: can be re-run safely.

UPDATE public.consolidado_programas
SET acreditable = TRUE
WHERE lower(trim(regexp_replace(program, '\s+', ' ', 'g'))) IN (
  'artes plásticas',
  'dirección de banda',
  'diseño gráfico',
  'licenciatura en música',
  'maestría en música',
  'música instrumental',
  'doctorado en ciencias agrarias y agroindustriales',
  'ingeniería agroindustrial',
  'ingeniería agropecuaria',
  'ingeniería forestal',
  'maestría en ciencias agrarias',
  'administración de empresas',
  'contaduría pública',
  'economía',
  'maestría en estudios interdisciplinarios del desarrollo',
  'maestría en gestión de organizaciones y proyectos',
  'turismo',
  'enfermería',
  'especialización en anestesiología',
  'especialización en cirugía general',
  'especialización en ginecología y obstetricia',
  'especialización en medicina familiar',
  'especialización en medicina interna',
  'especialización en pediatría',
  'fisioterapia',
  'fonoaudiología',
  'medicina',
  'licenciatura en etnoeducación',
  'antropología',
  'doctorado en antropología',
  'doctorado en ciencias humanas',
  'filosofía',
  'geografía del desarrollo regional y ambiental',
  'historia',
  'licenciatura en lenguas modernas con énfasis en inglés y francés',
  'licenciatura en literatura y lengua castellana',
  'maestría en antropología',
  'maestría en artes integradas con el ambiente',
  'maestría en ciencias humanas',
  'doctorado en ciencias de la educación',
  'biología',
  'doctorado en ciencias ambientales',
  'doctorado en ciencias matemáticas',
  'doctorado en ciencias química',
  'doctorado en etnobiología y estudios bioculturales',
  'ingeniería física',
  'licenciatura en ciencias naturales y educación ambiental',
  'licenciatura en educación artística',
  'licenciatura en educación básica primaria',
  'licenciatura en educación física, recreación y deportes',
  'licenciatura en matemáticas',
  'maestría en biología',
  'maestría en ciencias matemáticas',
  'maestría en ciencias química',
  'maestría en deporte y actividad física',
  'maestría en educación (mi)',
  'maestría en educación popular',
  'maestría en educación, estudios del cuerpo y la motricidad',
  'maestría en ingeniería física',
  'maestría en recursos hidrobiológicos continentales',
  'matemáticas',
  'química',
  'ciencia política',
  'comunicación social',
  'derecho',
  'geotecnología',
  'ingeniería ambiental',
  'ingeniería civil',
  'maestría en geomática',
  'maestría en ingeniería de la construcción',
  'maestría en ingeniería de pavimentos',
  'maestría en ingeniería de vías terrestres',
  'doctorado en ciencias de la electrónica',
  'doctorado en ingeniería telemática',
  'ingeniería de sistemas',
  'ingeniería electrónica y telecomunicaciones',
  'ingeniería en automática industrial',
  'maestría en automática',
  'maestría en computación',
  'maestría en electrónica y telecomunicaciones',
  'maestría en ingeniería telemática',
  'maestría en telecomunicaciones',
  'tecnología en telemática'
);
