-- 018_update_rc_resolution_values.sql
-- Actualiza la columna rc_resolution en la tabla consolidado_programas según el nombre del programa

-- Asegura que la columna rc_resolution permita los valores requeridos
ALTER TABLE consolidado_programas ALTER COLUMN rc_resolution TYPE varchar(32);

-- Actualizar cada programa con su rc_resolution correspondiente
-- Ejemplo: UPDATE consolidado_programas SET rc_resolution = '19202' WHERE program = 'Artes Plásticas';

UPDATE consolidado_programas SET rc_resolution = '19202' WHERE program = 'Artes Plásticas';
    UPDATE consolidado_programas SET rc_resolution = '19204' WHERE program = 'Maestría en Música';
    UPDATE consolidado_programas SET rc_resolution = '1042' WHERE program = 'Licenciatura en Música';
    UPDATE consolidado_programas SET rc_resolution = '1037' WHERE program = 'Música Instrumental';
    UPDATE consolidado_programas SET rc_resolution = '6400' WHERE program = 'Diseño Gráfico';
    UPDATE consolidado_programas SET rc_resolution = '6402' WHERE program = 'Dirección de Banda';
    UPDATE consolidado_programas SET rc_resolution = '13200' WHERE program = 'Ingeniería Agroindustrial';
    UPDATE consolidado_programas SET rc_resolution = '3293' WHERE program = 'Especialización en Sanidad en Producción Agraria Integrada';
    UPDATE consolidado_programas SET rc_resolution = '2116' WHERE program = 'Especialización en Gestión Integral del Recurso Hídrico';
    UPDATE consolidado_programas SET rc_resolution = '2305' WHERE program = 'Ingeniería Agropecuaria';
    UPDATE consolidado_programas SET rc_resolution = '9952' WHERE program = 'Maestría en Ciencias Agrarias';
    UPDATE consolidado_programas SET rc_resolution = '12973' WHERE program = 'Doctorado en Ciencias Agrarias y Agroindustriales';
    UPDATE consolidado_programas SET rc_resolution = '8482' WHERE program = 'Ingeniería Forestal';
    UPDATE consolidado_programas SET rc_resolution = '23503' WHERE program = 'Contaduría Pública';
    UPDATE consolidado_programas SET rc_resolution = '16033' WHERE program = 'Especialización en Gerencia de Impuestos';
    UPDATE consolidado_programas SET rc_resolution = '16039' WHERE program = 'Especialización en Revisoría Fiscal y Auditoría Internacional';
    UPDATE consolidado_programas SET rc_resolution = '16018' WHERE program = 'Especialización en Gerencia de Proyectos';
    UPDATE consolidado_programas SET rc_resolution = '8266' WHERE program = 'Especialización en Mercadeo Corporativo';
    UPDATE consolidado_programas SET rc_resolution = '11104' WHERE program = 'Especialización en Gerencia de Proyectos';
    UPDATE consolidado_programas SET rc_resolution = '18046' WHERE program = 'Administración de Empresas';
    UPDATE consolidado_programas SET rc_resolution = '2583' WHERE program = 'Maestría en Gestión de Organizaciones y Proyectos';
    UPDATE consolidado_programas SET rc_resolution = '2117' WHERE program = 'Maestría en Economía Regional y Políticas Públicas';
    UPDATE consolidado_programas SET rc_resolution = '7139' WHERE program = 'Maestría en Gestión del Conocimiento y la Innovación';
    UPDATE consolidado_programas SET rc_resolution = '8576' WHERE program = 'Economía';
    UPDATE consolidado_programas SET rc_resolution = '16177' WHERE program = 'Maestría en Estudios Interdisciplinarios del Desarrollo';
    UPDATE consolidado_programas SET rc_resolution = '11924' WHERE program = 'Turismo';
    UPDATE consolidado_programas SET rc_resolution = '19531' WHERE program = 'Maestría en Desarrollo Humano y Salud';
    UPDATE consolidado_programas SET rc_resolution = '12529' WHERE program = 'Fonoaudiología';
    UPDATE consolidado_programas SET rc_resolution = '15518' WHERE program = 'Especialización en Anestesiología';
    UPDATE consolidado_programas SET rc_resolution = '15502' WHERE program = 'Especialización en Pediatría';
    UPDATE consolidado_programas SET rc_resolution = '3736' WHERE program = 'Especialización en Ginecología y Obstetricia';
    UPDATE consolidado_programas SET rc_resolution = '5523' WHERE program = 'Especialización en Cirugía General';
    UPDATE consolidado_programas SET rc_resolution = '14238' WHERE program = 'Enfermería';
    UPDATE consolidado_programas SET rc_resolution = '9994' WHERE program = 'Especialización en Intervención del Lenguaje Infantil';
    UPDATE consolidado_programas SET rc_resolution = '10592' WHERE program = 'Especialización en Medicina Interna';
    UPDATE consolidado_programas SET rc_resolution = '10593' WHERE program = 'Especialización en Medicina Familiar';
    UPDATE consolidado_programas SET rc_resolution = '10687' WHERE program = 'Fisioterapia';
    UPDATE consolidado_programas SET rc_resolution = '16756' WHERE program = 'Especialización en Seguridad y Salud en el Trabajo';
    UPDATE consolidado_programas SET rc_resolution = '23423' WHERE program = 'Enfermería (S.Q)';
    UPDATE consolidado_programas SET rc_resolution = '15917' WHERE program = 'Licenciatura en Lenguas Modernas con énfasis en Inglés y Francés (Santander de Quilichao)';
    UPDATE consolidado_programas SET rc_resolution = '8267' WHERE program = 'Filosofía';
    UPDATE consolidado_programas SET rc_resolution = '11378' WHERE program = 'Geografía del Desarrollo Regional y Ambiental';
    UPDATE consolidado_programas SET rc_resolution = '15313' WHERE program = 'Doctorado en Antropología';
    UPDATE consolidado_programas SET rc_resolution = '6493' WHERE program = 'Maestría en Antropología';
    UPDATE consolidado_programas SET rc_resolution = '9951' WHERE program = 'Maestría en Ciencias Humanas';
    UPDATE consolidado_programas SET rc_resolution = '2585' WHERE program = 'Doctorado en Ciencias Humanas';
    UPDATE consolidado_programas SET rc_resolution = '6405' WHERE program = 'Licenciatura en Lenguas Modernas con Énfasis en Inglés y Francés';
    UPDATE consolidado_programas SET rc_resolution = '6404' WHERE program = 'Historia';
    UPDATE consolidado_programas SET rc_resolution = '9732' WHERE program = 'Maestría en Artes Integradas con el Ambiente';
    UPDATE consolidado_programas SET rc_resolution = '14237' WHERE program = 'Licenciatura en Literatura y Lengua Castellana';
    UPDATE consolidado_programas SET rc_resolution = '24484' WHERE program = 'Licenciatura en Etnoeducación y Ciencias Sociales';
    UPDATE consolidado_programas SET rc_resolution = '9085' WHERE program = 'Licenciatura en Etnoeducación y Ciencias Sociales';
    UPDATE consolidado_programas SET rc_resolution = '10048' WHERE program = 'Antropología';
    UPDATE consolidado_programas SET rc_resolution = '9133' WHERE program = 'Especialización en Educación Comunitaria';
    UPDATE consolidado_programas SET rc_resolution = '23384' WHERE program = 'Ingeniería Física';
    UPDATE consolidado_programas SET rc_resolution = '22115' WHERE program = 'Maestría en Educación Popular';
    UPDATE consolidado_programas SET rc_resolution = '2559' WHERE program = 'Maestría en Educación Popular (Santander de Quilichao)';
    UPDATE consolidado_programas SET rc_resolution = '5619' WHERE program = 'Maestría en Educación (MI)';
    UPDATE consolidado_programas SET rc_resolution = '7456' WHERE program = 'Biología';
    UPDATE consolidado_programas SET rc_resolution = '17049' WHERE program = 'Maestría en Ingeniería Física';
    UPDATE consolidado_programas SET rc_resolution = '17637' WHERE program = 'Maestría en Biología';
    UPDATE consolidado_programas SET rc_resolution = '23702' WHERE program = 'Maestría en Educación, Estudios del Cuerpo y la Motricidad';
    UPDATE consolidado_programas SET rc_resolution = '24184' WHERE program = 'Maestría en Educación Superior';
    UPDATE consolidado_programas SET rc_resolution = '2311' WHERE program = 'Licenciatura en Educación Física, Recreación y Deportes';
    UPDATE consolidado_programas SET rc_resolution = '2312' WHERE program = 'Licenciatura en Educación Artística';
    UPDATE consolidado_programas SET rc_resolution = '1109' WHERE program = 'Licenciatura en Ciencias Naturales y Educación Ambiental';
    UPDATE consolidado_programas SET rc_resolution = '1110' WHERE program = 'Licenciatura en Educación Básica Primaria';
    UPDATE consolidado_programas SET rc_resolution = '2571' WHERE program = 'Maestría en Deporte y Actividad Física';
    UPDATE consolidado_programas SET rc_resolution = '6543' WHERE program = 'Doctorado en Ciencias Matemáticas';
    UPDATE consolidado_programas SET rc_resolution = '7568' WHERE program = 'Matemáticas';
    UPDATE consolidado_programas SET rc_resolution = '8922' WHERE program = 'Química';
    UPDATE consolidado_programas SET rc_resolution = '9286' WHERE program = 'Especialización en Educación y Discapacidad';
    UPDATE consolidado_programas SET rc_resolution = '14447' WHERE program = 'Maestría en Ciencias Matemáticas';
    UPDATE consolidado_programas SET rc_resolution = '16903' WHERE program = 'Doctorado en Ciencias de la Educación';
    UPDATE consolidado_programas SET rc_resolution = '17692' WHERE program = 'Doctorado en Etnobiología y Estudios Bioculturales';
    UPDATE consolidado_programas SET rc_resolution = '17691' WHERE program = 'Doctorado en Ciencias Química';
    UPDATE consolidado_programas SET rc_resolution = '22249' WHERE program = 'Maestría en Recursos Hidrobiológicos Continentales';
    UPDATE consolidado_programas SET rc_resolution = '23635' WHERE program = 'Maestría en Ciencias Química';
    UPDATE consolidado_programas SET rc_resolution = '1125' WHERE program = 'Doctorado en Ciencias Ambientales';
    UPDATE consolidado_programas SET rc_resolution = '2015' WHERE program = 'Licenciatura en Matemáticas';
    UPDATE consolidado_programas SET rc_resolution = '21473' WHERE program = 'Maestría en Bioingeniería';
    UPDATE consolidado_programas SET rc_resolution = '8977' WHERE program = 'Derecho';
    UPDATE consolidado_programas SET rc_resolution = '7110' WHERE program = 'Comunicación Social';
    UPDATE consolidado_programas SET rc_resolution = '7108' WHERE program = 'Derecho';
    UPDATE consolidado_programas SET rc_resolution = '9958' WHERE program = 'Ciencia Política';
    UPDATE consolidado_programas SET rc_resolution = '11630' WHERE program = 'Especialización en Derecho de Familia';
    UPDATE consolidado_programas SET rc_resolution = '14229' WHERE program = 'Especialización en Gobierno y Políticas Públicas';
    UPDATE consolidado_programas SET rc_resolution = '23526' WHERE program = 'Especialización Derecho Procesal';
    UPDATE consolidado_programas SET rc_resolution = '9097' WHERE program = 'Especialización en Ingeniería de Vías Terrestres';
    UPDATE consolidado_programas SET rc_resolution = '14826' WHERE program = 'Maestría en Ingeniería Hidráulica e Hidrológica';
    UPDATE consolidado_programas SET rc_resolution = '16956' WHERE program = 'Maestría en Ingeniería Ambiental';
    UPDATE consolidado_programas SET rc_resolution = '9823' WHERE program = 'Ingeniería Ambiental';
    UPDATE consolidado_programas SET rc_resolution = '14165' WHERE program = 'Especialización en Estructuras';
    UPDATE consolidado_programas SET rc_resolution = '17486' WHERE program = 'Ingeniería Civil';
    UPDATE consolidado_programas SET rc_resolution = '19205' WHERE program = 'Maestría en Ingeniería de la Construcción';
    UPDATE consolidado_programas SET rc_resolution = '19206' WHERE program = 'Maestría en Ingeniería de Pavimentos';
    UPDATE consolidado_programas SET rc_resolution = '19316' WHERE program = 'Geotecnología';
    UPDATE consolidado_programas SET rc_resolution = '23675' WHERE program = 'Maestría en Ingeniería de Vías Terrestres';
    UPDATE consolidado_programas SET rc_resolution = '23673 (i)' WHERE program = 'Maestría en Ingeniería de Vías Terrestres';
    UPDATE consolidado_programas SET rc_resolution = '11559' WHERE program = 'Maestría en Geomática';
    UPDATE consolidado_programas SET rc_resolution = '2574' WHERE program = 'Especialización en Ingeniería de Recursos Hídricos';
    UPDATE consolidado_programas SET rc_resolution = '8598' WHERE program = 'Ingeniería Civil';
    UPDATE consolidado_programas SET rc_resolution = '17701' WHERE program = 'Arquitectura';
    UPDATE consolidado_programas SET rc_resolution = '9385' WHERE program = 'Ingeniería en Inteligencia Artificial y Ciencia de Datos';
    UPDATE consolidado_programas SET rc_resolution = '9064' WHERE program = 'Especialización en Redes y Servicios Telemáticos';
    UPDATE consolidado_programas SET rc_resolution = '14253' WHERE program = 'Especialización en Redes y Servicios Telemáticos';
    UPDATE consolidado_programas SET rc_resolution = '4006' WHERE program = 'Ingeniería Electrónica y Telecomunicaciones';
    UPDATE consolidado_programas SET rc_resolution = '16108' WHERE program = 'Maestría en Ingeniería Telemática';
    UPDATE consolidado_programas SET rc_resolution = '14594' WHERE program = 'Doctorado en Ciencias de la Computación';
    UPDATE consolidado_programas SET rc_resolution = '13233' WHERE program = 'Tecnología en Telemática';
    UPDATE consolidado_programas SET rc_resolution = '3248' WHERE program = 'Ingeniería de Sistemas';
    UPDATE consolidado_programas SET rc_resolution = '12658' WHERE program = 'Maestría en Electrónica y Telecomunicaciones';
    UPDATE consolidado_programas SET rc_resolution = '16771' WHERE program = 'Doctorado en Ingeniería Telemática';
    UPDATE consolidado_programas SET rc_resolution = '19209' WHERE program = 'Maestría en Telecomunicaciones';
    UPDATE consolidado_programas SET rc_resolution = '11564' WHERE program = 'Especialización en TIC para la Innovación Educativa';
    UPDATE consolidado_programas SET rc_resolution = '20074' WHERE program = 'Maestría en Automática';
    UPDATE consolidado_programas SET rc_resolution = '20075' WHERE program = 'Doctorado en Ciencias de la Electrónica';
    UPDATE consolidado_programas SET rc_resolution = '20747' WHERE program = 'Maestría en Computación';
    UPDATE consolidado_programas SET rc_resolution = '11015' WHERE program = 'Ingeniería en Automática Industrial';

END $$;
